---
# Gitpod Configuration
# ver: https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml

# Uso de imagen de Docker específica
# ver: https://hub.docker.com/u/gitpod
image: gitpod/workspace-java-17

# Comandos a ejecutar al inicio del proyecto
tasks:
  - name: Instala Spring Boot 
    command: sdk install springboot 

  - name: Compila proyecto sin ejecutar pruebas
    before: |
      sdk default java 17.0.8.fx-zulu
    init: ./mvnw package -DskipTests 

# Extensiones
vscode:
  extensions:
    - vscjava.vscode-java-debug
    - redhat.java@1.21.0
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - vscjava.vscode-spring-boot-dashboard
    - vmware.vscode-spring-boot
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-java-test
